# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-08 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Lotek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
