# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-08 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lotek', '0003_auto_20180608_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='randoms',
            field=models.IntegerField(default=0),
        ),
    ]
